# Generated by Django 5.0.7 on 2025-09-08 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_feedback_category_feedback_is_anonymous_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
